"""
Pydantic models for API request/response schemas and internal data transfer.
"""

from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Internal data-transfer objects (used between services)
# ---------------------------------------------------------------------------

class WhisperWord(BaseModel):
    """A single word from Whisper transcription with timing and confidence."""
    word: str
    start: float
    end: float
    probability: float


class TranscriptionResult(BaseModel):
    """Complete result from Whisper transcription."""
    transcript: str
    words: list[WhisperWord]


class PhonemeDetail(BaseModel):
    """Phoneme-level detail from Azure pronunciation assessment."""
    phoneme: str
    score: float
    issue: str = ""  # e.g., "substitution", "omission", "mispronunciation"


class AzureWordScore(BaseModel):
    """Per-word score from Azure pronunciation assessment."""
    word: str
    accuracy_score: float
    error_type: str = "None"  # "None", "Mispronunciation", "Omission", "Insertion"
    phonemes: list[PhonemeDetail] = Field(default_factory=list)


class AzureResult(BaseModel):
    """Aggregate result from Azure pronunciation assessment."""
    accuracy_score: float
    fluency_score: float
    completeness_score: float
    prosody_score: float
    words: list[AzureWordScore]


class FlaggedWord(BaseModel):
    """A word flagged for pronunciation issues, sent to LLM for explanation."""
    word: str
    start_time: float
    end_time: float
    score: float
    issue_type: str
    phoneme_detail: list[PhonemeDetail] = Field(default_factory=list)


class LLMFeedback(BaseModel):
    """Feedback generated by the LLM for flagged words."""
    summary: str
    word_feedback: dict[str, str] = Field(
        default_factory=dict,
        description="Mapping of word -> feedback string"
    )


# ---------------------------------------------------------------------------
# API response models
# ---------------------------------------------------------------------------

class WordResult(BaseModel):
    """A single word in the final API response."""
    word: str
    start: float
    end: float
    score: float
    issue: str
    feedback: str


class AssessmentResponse(BaseModel):
    """Successful assessment response returned to the client."""
    overall_score: float
    fluency: float
    completeness: float
    prosody: float
    summary: str
    transcript: str
    words: list[WordResult]
    scoring_unavailable: bool = False
    scoring_error: str = ""


class ErrorResponse(BaseModel):
    """Error response for validation failures and server errors."""
    error: str
    detail: str
